configuration:
  enabled: false
  bot:
    token: "token"
    game:
      enabled: true
      twitch: false
      url: "https://github.com/ProgrammingWizzard/MCCord"
      name: "Minecraft"
    modules:
      chat-module:
        enabled: false
        channel-id: "id of text-channel"
        discord: "**%nickname**: %message"
        minecraft: "&8[&6Discord&8] &7%nickname: &6%message"